
default_platform(:ios)

platform :ios do
  desc "Lane for iOS Firebase App Distribution"
  lane :firebase_distribution do
    Dir.chdir("..") do
      sh "flutter clean"
      sh "flutter pub get"
      sh "flutter build ios --release --no-tree-shake-icons"
    end
    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "ad-hoc"
    )
    firebase_app_distribution(
      app: "1:383408612193:ios:81a271d65d9459fc4c5b20",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      ios_artifact_path: "../build/ios/ipa/Runner.ipa",
      testers: "omar.ameer2333@gmail.com",
      release_notes: "This is the first iOS release using Fastlane. Enjoy! 🚀"
    )
  end
end
